---
apiVersion: v1
kind: Service
metadata:
  name: starter-service # Name of the service. Could be anything.
  labels:
    app: ta3-container #Name of ta3 container
spec:
  type: LoadBalancer # Type of service. This should always be LoadBalancer.
  loadBalancerIP: 10.108.34.48 # range of 10.108.34.40-49. If you use this, please mark your IP on Reserved IP section if you want your IP not to collide with someone else.
  selector:
    app: starter-container # This is where you define which container to link this service to. This must match the labels.app attribute of the pod you are trying to create the service for.
  ports:
    - name: http
      port: 8080 #represents that service can be accessed by other services in the cluster at port 8080.
      protocol: TCP
      targetPort: 8080 # The targetPort is 8080 which represents the service is actually running on port 8080 on pods
---
apiVersion: v1
kind: Pod
metadata:
name: starter-pod #can be anything
labels:
  app: starter-container #note that this attribute must match spec.selector attribute of the service
spec:
  restartPolicy: Never
  containers:
    - name: starter-container
      image: registry.datadrivendiscovery.org/cliu/starter:latest #replace me
      imagePullPolicy: Always
      command: [./start]
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          memory: 2Gi
          cpu: 2
  #...[add more containers if needed]

  imagePullSecrets:
    - name: regcred-cl
