apiVersion: v1
kind: Service
metadata:
  name: tufts-ta3-balancer
  labels:
    app: tufts-ta3
spec:
  loadBalancerIP: 10.108.34.41
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tufts-ta3
---
apiVersion: v1
kind: Pod
metadata:
  name: tufts-ta3
  labels:
    app: tufts-ta3
spec:
  restartPolicy: Always
  containers:
    # TUFTS TA3
    - name: tufts-ta3
      image: registry.datadrivendiscovery.org/fheimerl/tuftsgtwiscta3:latest
      imagePullPolicy: Always
      command: [./ta3_search]
      args:
        - dataset:__direct__
      env:
        - name: D3MRUN
          value: "ta2ta3"
        - name: D3MINPUTDIR
          value: "/input"
        - name: D3MOUTPUTDIR
          value: /output"
        - name: D3MLOCALDIR
          value: "/output/D3MLOCALDIR"
        - name: D3MSTATICDIR
          value: "/static"
        - name: D3MPROBLEMPATH
          value: "/input/TRAIN/problem_TRAIN/problemDoc.json"
        - name: D3MLOCALDIR
          value: "/output/D3MLOCALDIR"
        - name: D3MCPU
          value: "2"
        - name: D3MRAM
          value: "10Gi"
        - name: D3MTIMEOUT
          value: "600"
        - name: TA2_PORT
          value: "45042"
      volumeMounts:
        - name: input-data
          mountPath: /input
          readOnly: true
        - name: output-data
          mountPath: /output
          readOnly: false
        - name: static-data
          mountPath: /static
          readOnly: true
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          # that's what we've been testing on:
          memory: 5Gi
          cpu: 1
  imagePullSecrets:
    - name: regcred-cl
  volumes:
    - name: input-data
      hostPath:
        path: /d3m/datasets/seed_datasets_data_augmentation/DA_poverty_estimation
        type: Directory
    - name: static-data
      hostPath:
        path: /d3m/static-files
        type: Directory
    - name: output-data
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
