apiVersion: v1
kind: Pod
metadata:
  name: tufts-ta3-ci
  labels:
    app: tufts-ta3-ci
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred-cl
  volumes:
    - name: static-data
      hostPath:
        path: /opt/static_files/
        type: Directory
    - name: input-vol
      hostPath:
        path: /opt/datasets/seed_datasets_current/196_autoMpg
        type: Directory
    - name: output-vol
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
  containers:    
    - name: tufts-ta3
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/cliu/tuftsgtwiscta3:cl-master
      command: [./ta3_search]
      args:
        - dataset:__direct__
      volumeMounts:
        - name: input-vol
          mountPath: /input
          readOnly: true
        - name: output-vol
          mountPath: /output
          readOnly: false
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          # that's what we've been testing on:
          memory: 5Gi
          cpu: 1
      env:
        - name: TA2_PORT
          value: "45042"
  
