apiVersion: v1
kind: Pod
metadata:
  name: tufts-baseball
  labels:
    app: tufts-baseball
spec:
  restartPolicy: Never
  containers:       
    # TUFTS TA3
    - name: tufts-ta3
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/cliu/tuftsgtwiscta3:baseball
      command:
        [
          ./ta3_search shared/static/config_files/dev_mode/example_dev_classification_config.json,
        ]
      # args:
      #   - dataset:__direct__
      volumeMounts:
        - name: input-vol
          mountPath: /input
          readOnly: true
        - name: output-vol
          mountPath: /output
          readOnly: false
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          # that's what we've been testing on:
          memory: 5Gi
          cpu: 1
      env:
        - name: TA2_PORT
          value: "45042"
  imagePullSecrets:
    - name: regcred-cl
  volumes:
    - name: static-data
      hostPath:
        path: /opt/static_files/
        type: Directory
    - name: input-vol
      hostPath:
        path: /opt/datasets/seed_datasets_current/185_baseball
        type: Directory
    - name: output-vol
      persistentVolumeClaim:
        claimName: eval-output-pv-claim