apiVersion: v1
kind: Service
metadata:
  name: tufts-baseball
  labels:
    app: tufts-baseball
spec:
  loadBalancerIP: 10.108.25.34
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tufts-baseball
