apiVersion: v1
kind: Service
metadata:
  name: tufts-autompg
  labels:
    app: tufts-autompg
spec:
  loadBalancerIP: 10.108.25.33
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tufts-autompg
---
apiVersion: v1
kind: Pod
metadata:
  name: tufts-autompg
  labels:
    app: tufts-autompg
spec:
  restartPolicy: Never
  containers:
    - name: isi-ta2
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/kyao/ta3ta2/ta3ta2-v2019.4.4-image:latest
      env:
        - name: D3MRUN
          value: "ta2ta3"
        - name: D3MINPUTDIR
          value: "/input"
        - name: D3MOUTPUTDIR
          value: "/output"
        - name: D3MSTATICDIR
          value: "/static"
        - name: D3MPROBLEMPATH
          value: "/input/TRAIN/problem_TRAIN/problemDoc.json"
        - name: D3MLOCALDIR
          value: "/output/D3MLOCALDIR"
        - name: D3MCPU
          value: "8"
        - name: D3MRAM
          value: "56Gi"
        - name: D3MTIMEOUT
          value: "600"
        - name: D3MCONTEXT
          value: "EVALUATION"
      volumeMounts:
        - name: input-data
          mountPath: /input
          readOnly: true
        - name: output-data
          mountPath: /output
          readOnly: false
        - name: static-data
          mountPath: /static
          readOnly: true
      resources:
        requests:
          memory: 10Gi
          cpu: 4
      ports:
        - containerPort: 45042
          hostPort: 45042
    # TUFTS TA3
    - name: tufts-ta3
      imagePullPolicy: Always
      image: registry.datadrivendiscovery.org/ta3-submissions/ta3-tufts/may2019:latest
      command: [./ta3_search]
      args:
        - dataset:__direct__
      volumeMounts:
        - name: input-data
          mountPath: /input
          readOnly: true
        - name: output-data
          mountPath: /output
          readOnly: false
      ports:
        - name: http
          containerPort: 8080
      resources:
        requests:
          # that's what we've been testing on:
          memory: 2Gi
          cpu: 1
      env:
        - name: TA2_PORT
          value: "45042"
  imagePullSecrets:
    - name: regcred-cl
  volumes:
    - name: static-data
      hostPath:
        path: /opt/static_files/
        type: Directory
    - name: input-data
      hostPath:
        path: /opt/datasets/seed_datasets_current/196_autoMpg
        type: Directory
    - name: output-data
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
